language: go

go:
  - 1.7

env:
  global:
  - SSH_KEY="key"
  - ENCRYPTION_LABEL="6f2bf71e1293"
  - GIT_NAME="Peter Y. Chuang"
  - GIT_EMAIL="peteryuchuang@gmail.com"
  - SOURCE_DIR="public"
  - DEPLOY_BRANCH="source"

branches:
  only:
  - source

cache:
  directories:

install: 
- wget https://github.com/gohugoio/hugo/releases/download/v0.52/hugo_0.52_Linux-64bit.deb
- sudo dpkg -i hugo*.deb

before_install:
- openssl aes-256-cbc -K $encrypted_6f2bf71e1293_key -iv $encrypted_6f2bf71e1293_iv -in key.enc -out key -d
before_script:
- pip install --user pygments
- npm install -g gulp-cli
- npm install gulp
- npm install gulp-htmlmin
- npm install gulp-base64

script:
- hugo
- gulp deploy
- echo novelist.xyz > ./public/CNAME
- touch ./public/.nojekyll
- echo -e "# [Kritiker](https://kritiker.xyz)\n\nThis is the repository for the compiled HTML and static files of my website.\n\nFor the source of the website, please visit the [source branch](https://github.com/peterychuang/kritiker.xyz/tree/source)." > ./public/readme.md
- sh ./deploy.sh