baseURL = "https://kritiker.xyz"
languageCode = "en-gb"
title = "Kritiker"
theme = "criticism"
publishdir = "./_output/hugo-stage-1/"
pluralizelisttitles = "false"
footnoteReturnLinkContents = "^"

[params]
  description = "Reviews and essays on classical music - recordings, live performances, and everything else."
  subtitle = "Classical Music Reviews"
  author = "Peter Y. Chuang"
  Urlimg = "assets/img/"

[taxonomies]
  tag= "tag"
  category= "categories"
